---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-crds
  namespace: nginx-gw
spec:
  interval: 10m
  targetNamespace: nginx-gw
  sourceRef:
    kind: GitRepository
    name: nginxgw-crds
  path: "./config/crd/gateway-api/experimental"
  prune: true
  timeout: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginxgw-crds
  namespace: nginx-gw
spec:
  interval: 5m
  url: https://github.com/nginxinc/nginx-gateway-fabric
  ref:
    tag: v1.4.0