apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: nginx-gw
  name: nginx-gw
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: nginx-gw
    namespace: nginx-gw
  valuesFrom:
    - kind: ConfigMap
      name: nginx-gwvalues
      