apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  namespace: nginx-gw
  name: nginx-gw
spec:
  interval: 5m
  url: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
  ref:
    tag: 1.4.0