apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  namespace: nginx-gw
  name: nginx-gw
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/nginxinc/charts/nginx-gateway-fabric
  ref:
    tag: v1.4.0