apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: nginx-gw
  name: nginx-gw
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  chart:
    spec:
      chart: 'nginx-gateway-fabric'
      version: '1.4.0'
      sourceRef:
        kind: OCIRepository
        name: nginx-gw
        namespace: nginx-gw
      interval: 1m
  releaseName: "ngf"
  valuesFrom:
    - kind: ConfigMap
      name: nginx-gwvalues
      