apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: nginx-gw
  name: nginx-gw
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  chart:
    spec:
      chart: 'ingress-nginx'
      sourceRef:
        kind: HelmRepository
        name: nginx-gw
        namespace: nginx-gw
      interval: 1m
  releaseName: nginx-gw
  valuesFrom:
    - kind: ConfigMap
      name: nginx-gwvalues
      