apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yml
- helmrepo.yml
- ns.yml
commonLabels:
  nginx.kubernetes.name: "hell"
  nginx.kubernetes.env: "prd"
configMapGenerator:
- name: nginx-gw-values
  namespace: nginx-gw
  files: 
  - values.yaml=values.yml
configurations:
  - kustomizeconfig.yml