nginx:
  usage:
    clusterName: jupiter.hell.local
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
nginxGateway:
  replicaCount: 3
  gwAPIExperimentalFeatures: true