---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: metrics
  namespace: metrics
spec:
  parentRefs:
  - name: vault
    namespace: vault
    sectionName: https-m
  hostnames:
  - "metrics.hell.local"
  rules:
  - backendRefs:
    - name: metrics-metrics-server
      namespace: metrics
      port: 443