---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: metrics
  namespace: metrics
spec:
  parentRefs:
  - name: vault
    namespace: vault
    sectionName: https-m
  hostnames:
  - "metrics.hell.local"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: metrics-metrics-server
      namespace: metrics
      port: 443