apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: metrics
  name: metrics
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  chart:
    spec:
      chart: 'metrics-server'
      sourceRef:
        kind: HelmRepository
        name: metrics
        namespace: metrics
      interval: 1m
  releaseName: metrics
  valuesFrom:
    - kind: ConfigMap
      name: metrics-values
      