apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yml
- helmrepo.yml
- ns.yml
- ingress.yml
- issuer.yml
configMapGenerator:
- name: metrics-values
  namespace: metrics
  files: 
  - values.yaml=values.yml
configurations:
  - kustomizeconfig.yml