apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yml
- helmrepo.yml
- sealedsecretns.yml
commonLabels:
  vault.kubernetes.name: "hell"
  vault.kubernetes.env: "prd"
configMapGenerator:
- name: values
  namespace: sealed-secrets
  files: 
  - values.yml=values.yml
nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease