apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yml
- helmrepo.yml
- sealedsecretns.yml
commonLabels:
  vault.kubernetes.name: "hell"
  vault.kubernetes.env: "prd"
- name: values
  files: values=values.yml