apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: kube-system
  name: csi-driver-nfs
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  chart:
    spec:
      chart: 'csi-driver-nfs'
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: kube-system
      interval: 1m
  releaseName: csi-driver-nfs
  valuesFrom:
    - kind: ConfigMap
      name: csi-nfs-values