apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  namespace: kube-system
  name: csi-driver-nfs
spec:
  interval: 5m
  url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts