apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  namespace: vault
  name: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: hashicorp/vault
      version: 0.28.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
      interval: 1m
  values:
    replicaCount: 2