apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: vault
  name: vaultrelease
spec:
  interval: 5m
  chart:
    spec:
      chart: 'vault'
      version: 0.28.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
      interval: 1m
  releaseName: vault
  values:
    server:
      ha:
        enabled: true
        replicas: 2