apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: vault
  name: vaultrelease
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: 'vault'
      version: 0.28.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
      interval: 1m
  releaseName: vault
  valuesFrom:
    - kind: ConfigMap
      name: values