apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: vault
  name: vaultrelease
spec:
  interval: 5m
  chart:
    spec:
      chart: 'hashicorp/vault'
      version: 0.28.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
      interval: 1m
  releaseName: vault
  values:
    replicaCount: 2