apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  namespace: vault
  annotations: {}
    #cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jupiter.hell.local
    secretName: vault-tls
  rules:
  - host: jupiter.hell.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault-ui
            port:
              number: 7445