---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: vault
  annotations:
    cert-manager.io/inject-ca-from-secret: vault/vault-ca
webhooks:
- name: jupiter.hell.local
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault-active
      namespace: vault
      path: /
      port: 8200
  sideEffects: None
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-ca
  namespace: vault
  annotations:
    cert-manager.io/allow-direct-injection: "true"
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN4akNDQWllZ0F3SUJBZ0lVZGVUWVNoYTNEc0ZCc0VHMk5nbnRmblZKRUI0d0NnWUlLb1pJemowRUF3UXcKVWpFTE1Ba0dBMVVFQmhNQ1FWVXhEREFLQmdOVkJBY1RBMUZNUkRFUU1BNEdBMVVFQ2hNSFFtRnphRUp5YnpFUwpNQkFHQTFVRUN4TUpTVlJUZFhCd2IzSjBNUTh3RFFZRFZRUURFd1pMT0hNZ1EwRXdIaGNOTWpRd09UQTBNVEl6Ck5qSTBXaGNOTWpReE1EQTBNVEl6TmpVMFdqQlNNUXN3Q1FZRFZRUUdFd0pCVlRFTU1Bb0dBMVVFQnhNRFVVeEUKTVJBd0RnWURWUVFLRXdkQ1lYTm9Rbkp2TVJJd0VBWURWUVFMRXdsSlZGTjFjSEJ2Y25ReER6QU5CZ05WQkFNVApCa3M0Y3lCRFFUQ0JtekFRQmdjcWhrak9QUUlCQmdVcmdRUUFJd09CaGdBRUFIUjJyUk1XRHhyN3BCNm9UMHZVCmQyTzJMWnhFODU1dzl4bkl4S0xYM3JRQ1JzUlpTYmVacFRRMXFoTWl3QUtKMFByV3hBZ3BIb0gzQTYzTHBsak4KSndJUEFSWTUrVWdkcVdmZWlqTjk4Z05uYzlLOWx2d1V1ZXRSU0kyVUFIQk5IT2kwSHhWT0lGcVMzU2ZFUVRJYQo5VXB2eUsyMDZJR1drbzVBMmIyR2ZTRjU0d2hxbzRHWE1JR1VNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WCkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlM3L2Z0SXI5VG9ZUnlrRzY3bTZuZXh2czhSZ3pBZkJnTlYKSFNNRUdEQVdnQlM3L2Z0SXI5VG9ZUnlrRzY3bTZuZXh2czhSZ3pBeEJnTlZIUjRCQWY4RUp6QWxvQ013RElJSwphR1ZzYkM1c2IyTmhiREFUZ2hGemRtTXVZMngxYzNSbGNpNXNiMk5oYkRBS0JnZ3Foa2pPUFFRREJBT0JqQUF3CmdZZ0NRZ0UvdFNLTGtxcEt1djcxMHpBSUdyOUsyZ0Q0ZUFqQ2pxRFJnM05HTlcxNVdnelo0QjJZeXZWRENVb3cKUFlQK0g1Q0N4azRSZVFGSmg5S0drY3hmdWxlWElnSkNBWmRud1RtNEpLTm9wUzJiZWhhWG5vdjR4Z0FTOTl3cApFbHZsTzYvZ0RiSVl0RUp1b2lvbjJPVHNjdEcyUDFPTHQyOVFQV2Foc3FjdHFUQ05xVncxaWlJUgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: ""
  tls.crt: ""
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault
  namespace: vault
  annotations:
    cert-manager.io/issuer: "vault-issuer"
    cert-manager.io/common-name: "vault"
    cert-manager.io/private-key-algorithm: "ECDSA"
    cert-manager.io/private-key-size: "521"
    cert-manager.io/duration: "216h"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jupiter.hell.local
    secretName: vault-tls
  rules:
  - host: jupiter.hell.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault-active
            port:
              number: 8200