---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: vault
  annotations:
    cert-manager.io/inject-ca-from-secret: vault/vault-tls
webhooks:
- name: jupiter.hell.local
  admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: vault
      namespace: vault
      path: /ui/
      port: 8200
  sideEffects: None
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: vault
#  namespace: vault
#  annotations:
#    cert-manager.io/issuer: "vault-issuer"
#    cert-manager.io/common-name: "vault"
#    cert-manager.io/private-key-algorithm: "ECDSA"
#    cert-manager.io/private-key-size: "521"
#    cert-manager.io/duration: "216h"
#spec:
#  ingressClassName: nginx
#  tls:
#  - hosts:
#    - jupiter.hell.local
#    secretName: vault-tls
#  rules:
#  - host: jupiter.hell.local
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: vault-active
#            port:
#              number: 8200