apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yml
- helmrepo.yml
- vaultns.yml
- persistentvolume.yml
- cabundle.yml
- ingress.yml
- gateway.yaml
commonLabels:
  vault.kubernetes.name: "hell"
  vault.kubernetes.env: "prd"
configMapGenerator:
- name: values
  namespace: vault
  files: 
  - values.yaml=values.yml
configurations:
  - kustomizeconfig.yml