apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /rings/lucifer# Your NFS server path
    server: jupiter.hell.local
  persistentVolumeReclaimPolicy: Retain