apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /rings/lucifer
    server: jupiter.hell.local
  persistentVolumeReclaimPolicy: Retain