server:
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  ha:
    enabled: true
    replicas: 3
    apiAddr: "http://jupiter.hell.local:7443"
injector:
  enabled: "false"
ui:
  enabled: true
  serviceType: "LoadBalancer"
  externalPort: 7443
  serviceIPFamilyPolicy: "SingleStack"
  