server:
  dataStorage:
    enabled: true
    size: 2Gi
    mountPath: "/vault/data"
    accessMode: ReadWriteMany
    storageClass: nfs-csi
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  ha:
    enabled: true
    replicas: 3
    apiAddr: "http://jupiter.hell.local:7443"
    raft: 
      enabled: true
      setNodeId: true
      config: |
        cluster_name = "jupiter.hell.local"
        storage "raft" {
          path    = "/vault/data/"
        }
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = "true"
        }
        service_registration "kubernetes" {}
injector:
  enabled: "false"
ui:
  enabled: true
  serviceType: "LoadBalancer"
  externalPort: 7443
  serviceIPFamilyPolicy: "SingleStack"

