apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  namespace: ingress-nginx
  name: ingress-nginx
spec:
  driftDetection:
    mode: enabled
  interval: 5m
  chart:
    spec:
      chart: 'ingress-nginx'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 1m
  releaseName: ingress-nginx
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-values