controller:
  extraArgs:
    default-ssl-certificate: vault/vault-ca
  admissionWebhooks:
    annotations:
      cert-manager.io/inject-ca-from-secret: vault/vault-ca
    patch:
      tolerations:
        - key: "node-role.kubernetes.io"
          value: worker
          operator: Equal
          effect: NoSchedule
  tolerations:
    - key: "node-role.kubernetes.io"
      value: worker
      operator: Equal
      effect: NoSchedule
defaultBackend:
  tolerations:
    - key: "node-role.kubernetes.io"
      value: worker
      operator: Equal
      effect: NoSchedule