controller:
  admissionWebhooks:
    patch:
      tolerations:
        - key: "node-role.kubernetes.io"
          value: worker
          operator: Equal
          effect: NoSchedule
  tolerations:
    - key: "node-role.kubernetes.io"
      value: worker
      operator: Equal
      effect: NoSchedule
defaultBackend:
  tolerations:
    - key: "node-role.kubernetes.io"
      value: worker
      operator: Equal
      effect: NoSchedule