---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: rulediscovery
spec:
  order: 1
  types:
  - Ingress
  - Egress
  ingress:
  - action: Log
  - action: Allow
  egress:
  - action: Log
  - action: Allow