---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-busybox-egress
  namespace: advanced-policy-demo
spec:
  types:
  - Egress
  egress:
  - action: Allow
    protocol: TCP
    source:
      selector: service == 'access'
    destination:
      ports:
      - 443
  - action: Log
  - action: Den