---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: deny-app-policy
  namespace: advanced-policy-demo
spec:
  order: 99
  types:
  - Ingress
  - Egress
  egress:
  - action: Log
    protocol: TCP
    destination:
      nets:
      - 10.96.0.1/32
      ports:
      - 443
  - action: Allow
    protocol: TCP
    destination:
      nets:
      - 10.96.0.1/32
      ports:
      - 443
  - action: Allow
    protocol: UDP
    destination:
      selector: 'k8s-app == "kube-dns"'
      ports:
      - 53
  - action: Allow
    protocol: TCP
    destination:
      selector: 'k8s-app == "kube-dns"'
      ports:
      - 53
  - action: Log
  - action: Deny
  ingress:
  - action: Log
  - action: Deny