---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-k8s-apiserver
  namespace: cert-manager
spec:
  order: 1
  types:
    - Egress
  selector: app == 'cainjector'
  egress:
    - action: Log
      protocol: TCP
      destination:
        nets:
          - 10.96.0.1/32
        ports:
          - 443
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 10.96.0.1/32
        ports:
          - 443
---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: allow-k8s-apiserver2
  namespace: advanced-policy-demo
spec:
  order: 1
  types:
    - Egress
  egress:
    - action: Log
      protocol: TCP
      destination:
        nets:
          - 10.96.0.1/32
        ports:
          - 443
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 10.96.0.1/32
        ports:
          - 443