---
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: deny-app-policy
  namespace: advanced-policy-demo
spec:
  order: 1
  types:
  - Egress
  egress:
  - action: Log
    protocol: TCP
    destination:
      nets:
      - 10.96.0.0/24
      ports:
      - 443
  - action: Allow
    protocol: TCP
    destination:
      nets:
      - 10.96.0.0/24
      ports:
      - 443