---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: dockervault
  namespace: flux-system
spec:
  image: hashicorp/vault
  interval: 5m0s
  exclusionList:
    - "^.*\\.(sig)$"
    - "^1\\.[2-9]\\.\\d*$"
    - "^1\\.[2-9]$"
    - "^1\\.[2-9]\\.\\d*-rc[0-9]$"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: vaultdeploy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: dockervault
  policy:
    semver:
      range: 1.17.x