---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-issuer-sa
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-issuer-r
  namespace: vault
rules:
  - apiGroups: ['']
    resources: ['serviceaccounts/token']
    resourceNames: ['vault-issuer-sa']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-issuer-rb
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-issuer-r
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: vault
spec:
  vault:
    path: pki_int/sign/vault
    server: https://jupiter.hell.local:8443/
    caBundleSecretRef:
      key: ca.crt
      name: vault-tls
    auth:
      kubernetes:
        role: vault-issuer-role
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer-sa
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-acme
  namespace: vault
spec:
  acme:
    server: https://jupiter.hell.local:8443/pki_int/acme/directory
    caBundleSecretRef:
      key: ca.crt
      name: vault-tls
    privateKeySecretRef:
      name: vault-acme-key
