apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease.yml
- helmrepo.yml
commonLabels:
  vault.kubernetes.name: "hell"
  vault.kubernetes.env: "prd"
configMapGenerator:
- name: cert-mgr-values
  namespace: kube-system
  files: 
  - values.yaml=values.yml
configurations:
  - kustomizeconfig.yml