crds:
  enabled: true
tolerations:
- key: "node-role.kubernetes.io"
  value: "worker"
  operator: "Exists"
  effect: "NoSchedule"
cert-manager:
  namespace: cert-manager
webhook:
  hostNetwork: true
  securePort: 10260
  tolerations:
  - key: "node-role.kubernetes.io"
    value: "worker"
    operator: "Exists"
    effect: "NoSchedule"
cainjector:
  tolerations:
  - key: "node-role.kubernetes.io"
    value: "worker"
    operator: "Exists"
    effect: "NoSchedule"
startupapicheck:
  tolerations:
  - key: "node-role.kubernetes.io"
    value: "worker"
    operator: "Exists"
    effect: "NoSchedule"
prometheus:
  enabled: false

