crds:
  enabled: true
tolerations:
- key: "node-role.kubernetes.io"
  value: worker
  operator: Equal
  effect: NoSchedule
cert-manager:
  namespace: cert-manager
webhook:
  hostNetwork: true
  securePort: 10260
  tolerations:
  - key: "node-role.kubernetes.io"
    value: worker
    operator: Equal
    effect: NoSchedule
cainjector:
  tolerations:
  - key: "node-role.kubernetes.io"
    value: worker
    operator: Equal
    effect: NoSchedule
startupapicheck:
  tolerations:
  - key: "node-role.kubernetes.io"
    value: worker
    operator: Equal
    effect: NoSchedule
prometheus:
  enabled: false
config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true